version: '3.7'
services:
  mongodb:
    container_name: nyup-dev-mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
    volumes:
      - 'nyup-mongodb:/data/db:rw'
      - 'nyup-mongoconfig:/data/configdb:rw'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'

  redis:
    container_name: nyup-dev-redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'nyup-redis:/data:rw'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'

# By default stored in var/lib/docker/volumes
volumes:
  nyup-mongodb:
  nyup-mongoconfig:
  nyup-redis:
