version: '3.7'
services:
  mongodb:
    container_name: nyup-mongodb
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
    volumes:
      - 'nyup_mongodb:/data/db:rw'

  redis:
    container_name: nyup-redis
    image: redis:latest
    volumes:
      - 'nyup_redis:/data:rw'

volumes:
  nyup_mongodb:
  nyup_redis:
