version: '3.7'
services:
  postgres:
    container_name: nyup-postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - 'nyup_postgres:/var/lib/postgresql/data:rw'
    environment:
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=nyup'

# By default stored in var/lib/docker/volumes
volumes:
  nyup_postgres:
